### ISSUE TITLE
[Now Playing Script] Script don't change anything

### ISSUE THREAD

**Issue by prinzpi** [SacredSkull/sinusbot-scripts#2]
Hi,

I just have the problem that the script is not working for me.
I have setup everything as explained, but there aren't any changes.
Or do I miss maybe something?!
The Bot have enough permissions to change the name of the channel.

Screenshots below, I'm using the newest Sinusbot version (should be 0.11.0-8e5f1a2)
Regarding the "now Playing" i can only see following in the log files:
`Loading script Now_Playing_[Cleans_Bad_Tags]_[Custom_Display_Formats]_[TTS_Announce]`

<img width="408" alt="1" src="https://user-images.githubusercontent.com/12089703/34648971-5821df92-f3a5-11e7-82ed-b57a0c730454.PNG">
<img width="392" alt="2" src="https://user-images.githubusercontent.com/12089703/34648972-583df074-f3a5-11e7-8396-8ef484d73107.PNG">
<img width="941" alt="3" src="https://user-images.githubusercontent.com/12089703/34648973-58588e2a-f3a5-11e7-9f1d-796e3404dfd0.PNG">
<img width="449" alt="4" src="https://user-images.githubusercontent.com/12089703/34648974-58727934-f3a5-11e7-8b41-830be014f34a.PNG">

**Comment by SacredSkull** [comment]
Are you sure you have the latest version of Now Playing? At the top of your first image, it shows "Now Playing - 0.4" which is really old. Maybe that's an old screenshot?

Try downloading a fresh copy either from the Sinus forums or [directly from here (right click and save as)](https://raw.githubusercontent.com/SacredSkull/sinusbot-scripts/master/display/NowPlaying.js). Delete the original version to make sure it isn't the problem.

If it still doesn't work after showing at least "Now Playing - 0.6" I'll look into it further. It shouldn't matter, but is your server on Windows or Linux?

**Comment by prinzpi** [comment]
Ahh, it's working now.
By the default addon site the version 0.4 will be downloaded.. :upside_down_face: 

Thank you for the fast response.

**Comment by SacredSkull** [comment]
No problem!
