### ISSUE TITLE
Regex at 268 causes unwanted behavior

### ISSUE THREAD

**Issue by sruusk** [SacredSkull/sinusbot-scripts#4]
https://github.com/SacredSkull/sinusbot-scripts/blob/ea60f6b2796a1ab23fedd491892e9e5928f98a12/display/NowPlaying.js#L268

Causes characters like `ä`, `ö` and `å` to be filtered from the middle of words.

**Comment by Bluscream** [comment]
> https://github.com/SacredSkull/sinusbot-scripts/blob/ea60f6b2796a1ab23fedd491892e9e5928f98a12/display/NowPlaying.js#L268
> 
> Causes characters like `ä`, `ö` and `å` to be filtered from the middle of words.

Well `\w` does only include the english alphabet and digits. So it will also not allow russian letters or chinese, etc.

You can just remove that check if you need other languages than english
